run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - misspell
    - revive

issues:
  exclude-rules:
    # Test helpers intentionally ignore some errors
    - path: _test\.go
      linters:
        - errcheck
    # Wails-generated app.go has code that appears unused from static analysis
    - path: app\.go
      linters:
        - unused
